<a href="https://colab.research.google.com/github/KavyaSmruthi694/ICP-1/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

random_vector = np.random.randint(1, 21, size=15)

# Step 1: Reshaping the array to 3 by 5
matrix = random_vector.reshape(3, 5)

# Step 2: Printing the shape of the array
print("Shape of the matrix:", matrix.shape)

# Step 3: Replacing the max in each row with 0
for row_index in range(matrix.shape[0]):
    max_pos = np.argmax(matrix[row_index])
    matrix[row_index, max_pos] = 0
print("Modified matrix:\n", matrix)


Shape of the matrix: (3, 5)
Modified matrix:
 [[12  3  0  3  2]
 [ 0  8 14 20 19]
 [ 8 15 15  9  0]]


In [13]:
import numpy as np

# Creating a 4x3 array with random integers and 4-byte integer type
matrix_4x3 = np.random.randint(10, 100, size=(4, 3), dtype=np.int32)

# Printing shape, type, and data type
print("Matrix shape:", matrix_4x3.shape)
print("Matrix type:", type(matrix_4x3))
print("Element data type:", matrix_4x3.dtype)


Matrix shape: (4, 3)
Matrix type: <class 'numpy.ndarray'>
Element data type: int32


In [16]:
import numpy as np

matrix = np.array([[3, -2],
                   [1,  0]])
eigen_vals, eigen_vecs = np.linalg.eig(matrix)
print("Input Matrix:")
print(matrix)
print("\nEigenvalues of the matrix:")
for i, val in enumerate(eigen_vals):
    print(f"λ{i+1} = {val:.4f}")
print("\nRight Eigenvectors (each column corresponds to an eigenvalue):")
for i in range(eigen_vecs.shape[1]):
    print(f"Eigenvector {i+1} (for λ{i+1}): {eigen_vecs[:, i]}")



Input Matrix:
[[ 3 -2]
 [ 1  0]]

Eigenvalues of the matrix:
λ1 = 2.0000
λ2 = 1.0000

Right Eigenvectors (each column corresponds to an eigenvalue):
Eigenvector 1 (for λ1): [0.89442719 0.4472136 ]
Eigenvector 2 (for λ2): [0.70710678 0.70710678]


In [17]:
import numpy as np
array = np.array([[0, 1, 2],
                  [3, 4, 5]])
diagonal_elements = np.diag(array)
diagonal_sum = np.sum(diagonal_elements)
print("Array:")
print(array)
print("\nDiagonal elements:", diagonal_elements)
print("Sum of diagonal elements:", diagonal_sum)


Array:
[[0 1 2]
 [3 4 5]]

Diagonal elements: [0 4]
Sum of diagonal elements: 4


In [20]:
import numpy as np
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])
print("Original Array:")
print(original_array)
print("Shape:", original_array.shape)
new_shape = (2, 3)
reshaped_array = original_array.reshape(new_shape)
print("\nReshaped Array:")
print(reshaped_array)
print("New Shape:", reshaped_array.shape)


Original Array:
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)

Reshaped Array:
[[1 2 3]
 [4 5 6]]
New Shape: (2, 3)
