<a href="https://colab.research.google.com/github/KavyaSmruthi694/ICP-1/blob/main/700772834_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:

def fullname(first_name, last_name):
    return first_name + " " + last_name

def string_alternative(full_name):
    return full_name[::2]

def main():
    first_name = input("Enter first name: ")
    last_name = input("Enter last name: ")

    full_name = fullname(first_name, last_name)
    print("Full name:", full_name)

    print("Output:", string_alternative(full_name))

main()



Enter first name: Good
Enter last name: evening
Full name: Good evening
Output: Go vnn


In [19]:
file = open("input.txt", "r")
lines = file.readlines()
file.close()

for line in lines:
    print(line.strip())

print("Word_Count:")

word_count = {}

for line in lines:
    words = line.split()
    for word in words:
        if word in word_count:
            word_count[word] = word_count[word] + 1
        else:
            word_count[word] = 1

out = open("output.txt", "w")

for line in lines:
    out.write(line)

out.write("\nWord_Count:\n")

for word in word_count:
    print(word, ":", word_count[word])
    out.write(word + ": " + str(word_count[word]) + "\n")

out.close()


Python Course
Deep Learning Course
Word_Count:
Python : 1
Course : 2
Deep : 1
Learning : 1


In [31]:
L1 = [float(x) for x in input("Enter heights in inches: ").split(",")]

L2 = []
for h in L1:
    L2.append(round(h * 2.54, 2))

L3 = [round(h * 2.54, 2) for h in L1]

print("Output:", L2)
print("Output:", L3)




Enter heights in inches: 150,155, 145, 148
Output: [381.0, 393.7, 368.3, 375.92]
Output: [381.0, 393.7, 368.3, 375.92]


In [43]:
class Employee:

    emp_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.emp_count += 1

    def average_salary(self, salaries):
        return sum(salaries) / len(salaries)

    def display(self):
        print("Name:", self.name)
        print("Family:", self.family)
        print("Salary:", self.salary)
        print("Department:", self.department)
        print()


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)



e1 = Employee("Kavya", "Sreeramula", 60000, "HR")

f1 = FulltimeEmployee("Akhil", "Sai", 80000, "IT")
f2 = FulltimeEmployee("Teja", "Sai", 90000, "Finance")

e1.display()
f1.display()
f2.display()

salaries = [60000, 80000, 90000]
print("Average Salary:", e1.average_salary(salaries))

print("Total Employees:", Employee.emp_count)


Name: Kavya
Family: Sreeramula
Salary: 60000
Department: HR

Name: Akhil
Family: Sai
Salary: 80000
Department: IT

Name: Teja
Family: Sai
Salary: 90000
Department: Finance

Average Salary: 76666.66666666667
Total Employees: 3


In [42]:
import numpy as np

arr = np.round(np.random.uniform(1, 20, 20), 1)

print("Original vector:\n", arr)

arr = arr.reshape(4, 5)

print("\nReshaped array (4x5):\n", arr)

row_max_indices = np.argmax(arr, axis=1)
arr[np.arange(4), row_max_indices] = 0

print("\nAfter replacing max in each row with 0:\n", arr)


Original vector:
 [14.2  9.4  1.7 16.6  2.9 18.3  9.6  4.8  2.  17.1  1.2  5.4  6.6 15.5
  2.8 13.4  1.4  8.7  5.4  5.7]

Reshaped array (4x5):
 [[14.2  9.4  1.7 16.6  2.9]
 [18.3  9.6  4.8  2.  17.1]
 [ 1.2  5.4  6.6 15.5  2.8]
 [13.4  1.4  8.7  5.4  5.7]]

After replacing max in each row with 0:
 [[14.2  9.4  1.7  0.   2.9]
 [ 0.   9.6  4.8  2.  17.1]
 [ 1.2  5.4  6.6  0.   2.8]
 [ 0.   1.4  8.7  5.4  5.7]]
